const sidebars = {
  apiSidebar: [
    'intro',
    {
      type: 'category',
      label: 'API Reference',
      items: [
        {
          type: 'autogenerated',
          dirName: 'api',
        },
      ],
    },
    {
      type: 'category',
      label: '🤖 Easy SDK Generated',
      collapsed: false,
      items: [
        'easy_sdk/intro',
        {
          type: 'category', 
          label: 'API Reference',
          items: [
            'easy_sdk/api/products/index',
            'easy_sdk/api/users/index',
            'easy_sdk/api/orders/index',
            'easy_sdk/api/reviews/index',
          ],
        },
      ],
    },
  ],
};

module.exports = sidebars;